### ISSUE TITLE
Animation bar removal

### ISSUE THREAD

**Issue by shash08** [advaithm582/DARVIS#18]
Animation bar pushing down webpage and hover background added

**Comment by advaithm582** [comment]
![image](https://user-images.githubusercontent.com/83835839/128387573-3ee72ad1-84d3-45d8-9c1f-37e2ec81a96d.png)
Image

**Comment by shash08** [comment]
My commit in title-fix branch closes the issue

**Comment by shash08** [comment]
Merged and Done
