### ISSUE TITLE
Non-sticky footer

### ISSUE THREAD

**Issue by advaithm582** [advaithm582/DARVIS#7]
![image](https://user-images.githubusercontent.com/83835839/128213792-f424cb3f-01f2-4331-9464-63c6d3070574.png)
What is happening: The footer does not stick to bottom
Expected behaviour: Footer should stick to bottom
Proposed Solution: https://getbootstrap.com/docs/5.1/examples/sticky-footer/

**Comment by akhichit2008** [comment]
Fixed this issue successfully

**Comment by shash08** [comment]
Akhil's code in bug7-fix branch resolves the issue

**Comment by shash08** [comment]
> Akhil's code in bug7-fix branch resolves the issue

done...
