### ISSUE TITLE
Extra space in navbar 2 on scrolling down

### ISSUE THREAD

**Issue by advaithm582** [advaithm582/DARVIS#8]
![image](https://user-images.githubusercontent.com/83835839/128215884-1578f2fa-b021-41e4-b517-1c5a9c68f4bf.png)
What's happening: On scrolling, space where the DAV logo was is still there, leading to poor UI/UX
Expected behaviour: Gap should not be there (or) The text should be centred.
Possible solution @akhichit2008 @shash08 please discuss.

**Comment by shash08** [comment]
![image](https://user-images.githubusercontent.com/71306066/128365992-6b77e186-b87e-4d9c-aa1f-804e620235c4.png)


UI change solved the issue

**Comment by shash08** [comment]
Done by UI change
